# Create a GitHub action to email a report from a file at 6 a.m. daily

name: Email Daily Report
on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  email_daily_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Email daily report
        run: |
          echo "Good morning, here is the daily report" >